name: Create encrypted rule package

on:
  workflow_dispatch:
  schedule:
    - cron: '0 40 * * *'
jobs:
  zip-and-commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: 'Yamato-Security/hayabusa-rules'

      - name: Extract directory
        run: |
          mkdir extracted
          cp -r ./config ./extracted
          cp -r ./hayabusa ./extracted
          cp -r ./sigma ./extracted

      - name: Zip directory
        run: |
          sudo apt-get install zip
          zip -r -P yamato-security-hayabusa encrypted-hayabusa-rules.zip ./extracted

      - name: Checkout self repository
        uses: actions/checkout@v4
        with:
          path: './self'

      - name: Copy zip to self repository
        run: |
          cp ./encrypted-hayabusa-rules.zip ./self

      - name: Configure Git
        run: |
          cd ./self
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Commit changes
        run: |
          cd ./self
          git add encrypted-hayabusa-rules.zip
          git commit -m "Automated update"

      - name: Push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./self
          git push origin main
